config/routes.rb
  match 'users/verify_easy' => 'users#verify_easy'
  match 'users/create_easy' => 'users#create_easy'
  match 'users/account_easy' => 'users#account_easy'
  match 'users/leaderboard' => 'users#leader_board' , :format => 'json'
  match '/leaderboard/show' => 'users#leader_board_show'
  match 'users/earnmeedpoints' => 'users#earn_meed_points'
  match 'users/promotion' => 'users#promotion'
  match 'users/verify' => 'users#verify'
  match 'users/verify/again' => 'users#verifyagain'
  match 'users/checkhandle/:handle' => 'users#check_handle'
  match 'users/get_current_user' => 'users#get_current_user', :format => 'json'
  match 'users/increment/meed_points' => 'notifications#increment_meed_points', :format => 'json'
  match '/invites' => 'users#invite'
  match '/login' => redirect("/")
  match '/enterprise-signup' => 'home#enterprise_pointer'

  match '/emails/unsubscribe' => 'home#unsubscribe'
  match '/emails/subscribe' => 'home#subscribe'
  match '/jobs' => 'home#dash'
  match '/contactus' => 'home#contact_us'
  match '/contact' => 'home#contact'
  match '/ftue/update' => 'first_user_experiences#ftue_update'
  match '/about/product' => 'home#about_product'
  match '/about/version' => 'home#show_version'
  match '/school/verify' => 'schools#verify'
  match '/school/:school_id' => 'schools#index'
  match '/school/lookup/email' => 'schools#lookup', :format => 'json'
  match 'users/account' => 'users#account', :format => 'json'
  match 'users/influencers/account' => 'users#influencer_account', :format => 'json'
  match 'users/influencers/expertise/save' => 'users#influencer_expertise_save', :format => 'json'
  match 'users/create' => 'users#create'
  match '/login/verify' => 'sessions#create'

  match '/majors' => 'majors#index'
  match '/majors/degrees' => 'majors#majors_degrees', :format => 'json'
  match '/majors/types' => 'majors#majors_types', :format => 'json'

  match '/insights' => 'home#insights'
  match '/questions' => 'questions#dash'
  match '/connections' => 'connections#start'
  match '/connections/gmail' => 'connections#gmail_import'
  match '/connections/save' => 'connections#save'
  match '/connections/invited' => 'connections#invited'
  match '/contacts/failure' => 'connections#failure'
  match 'contacts/gmail/callback' => 'connections#gmail_import_callback'
  match 'contacts/auth/gmail' => 'connections#gmail_import_auth'
  match '/track/click/:data' => 'tracking#track_click'

  match '/auth/linkedin/callback' => 'sessions#social_sign_up', :format => 'json'
  match '/auth/github/callback' => 'sessions#social_sign_up'
  match '/auth/twitter/callback' => 'sessions#social_sign_up'
  match '/auth/callback' => 'sessions#social_sign_up', :format => 'json'

  match '/auth/linkedin/' => 'profiles#linkedin_import'
  match '/auth/twitter/' => 'profiles#linkedin_import'
  match '/auth/github/' => 'profiles#linkedin_import'
  match '/resume/upload/' => 'profiles#resume_upload', :format => 'json'

  match '/auth/failure' => 'profiles#linkedin_failure'

  match '/settings' => 'home#settings'
  match '/settings/:id/update' => 'home#update_settings'
  match '/settings/deactivate_survey' => 'home#deactivate_survey'

  match '/post/publish' => 'posts#publish_story'
  match '/post/job' => 'posts#post_job'
  match '/post/:id/update' => 'posts#update_story'
  match '/show/stories' => 'articles#show_stories'
  match '/scrape' => 'scrape#scrape'

  match '/invite' => 'home#invite_users'
  match '/waitlist/add' => 'home#add_waitlist_users'
  match '/invite/friends' => 'home#invite_users_mini'
  match '/facebook/friends/save' => 'connections#save_facebook'
  match '/ineedmeed' => 'home#need_meed'
  match '/waitlist_status' => 'home#need_meed_status'
  match '/waitlist/verify' => 'users#waitlist_verify'

  match '/hackathon/:id' => 'hackathon#show'
  match '/home' => 'home#dash'
  match '/activity' => 'feed#activity'
  match '/feed' => 'feed#feed'
  match '/submit/post(/:collection_id)' => 'articles#create_article', as: :create_article
  match '/articles/publish' => 'articles#publish_article'
  match '/articles/:id' => 'articles#show_article'
  match '/articles/:id/edit' => 'articles#edit_article'

  match '/logout' => 'sessions#destroy'
  match '/demigod/usc_auto_session' => 'sessions#demo'
  match '/edit' => 'profiles#edit'
  match '/view' => 'profiles#view'
  match '/share' => 'profiles#share'
  match '/meedfair' => 'home#careerfair'
  match '/jobinbox' => 'home#dash'
  match '/messages' => 'messages#messages'
  match '/profile' => 'profiles#profile'
  match '/influencers' => 'influencers#index'

  match '/:id/collection/:slug_id/:collection_id'  => 'collections#show_collection_full', as: :show_collection_full
  match '/:id/ama/:event_id' => 'profiles#view', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id' => 'profiles#view', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/follow' => 'profiles#follow_user', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/unfollow' => 'profiles#unfollow_user', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/invite' => 'profiles#invite_user', :constraints => {:id => /[^\/]*/}, as: 'user'

  match '/:id/:year/:month/:day/:article_id' => 'articles#show_story', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/story/:id/:year/:month/:day/:article_id' => 'articles#show_story', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/auth' => 'profiles#auth_view', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/contact' => 'profiles#contact_profile'
  match '/:id/contact/email' => 'profiles#send_email'
  match '/:id/viewers' => 'home#viewers'
  match '/:id/jobviews' => 'home#job_views'

  match '/ama/vmk-google' => 'events#show_ama'
  match '/ama/follow/:ama_id' => 'events#follow_ama'
  match '/user/recommendations'  => 'users#recommended_users', :format => 'json'
  match '/user/lead/recommendations'  => 'users#recommended_lead_users', :format => 'json'

  match '/profiles/objective/save' => 'profiles#save_objective'
  match '/profiles/bio/save' => 'profiles#save_bio'
  match '/profiles/headline/save' => 'profiles#save_headline'
  match '/profiles/publication/save' => 'profiles#save_publication'
  match '/profiles/internship/save' => 'profiles#save_internship'
  match '/profiles/course/save' => 'profiles#save_course'
  match '/profiles/experience/save' => 'profiles#save_experience'
  match '/profiles/education/save' => 'profiles#save_education'
  match '/profiles/header/save' => 'profiles#save_header'
  match '/profiles/photo/save' => 'photos#save_profile_photo'
  match '/articles/photo/save' => 'photos#save_article_photo'
  match '/feed/files/save' => 'feed#save_meed_files'

  match '/profiles/course/invites/:course_id' => 'courses#course_invites', :format => 'json'
  match '/course/invite/:invite_id/remind' => 'courses#invite_reminder', :format => 'json'
  match '/course/invite' => 'courses#create_invite', :format => 'json'

  match '/profiles/bundle' => 'profiles#show_profile_bundle'
  match '/comments/show' => 'comments#show_comments'
  match '/comments/create' => 'comments#create'
  match '/comments/:id/update' => 'comments#update'
  match '/comments/delete' => 'comments#delete'

  match '/company/:id' => 'companies#view', :constraints => {:id => /[^\/]*/}
  match '/company/follow/:id' => 'companies#follow', :constraints => {:id => /[^\/]*/}
  match '/company/:id/auth' => 'companies#auth_view', :constraints => {:id => /[^\/]*/}
  match '/company/unfollow/:id' => 'companies#unfollow', :constraints => {:id => /[^\/]*/}
  match '/user/company/recommendations'  => 'companies#recommended_companies', :format => 'json'
  match '/company/list/all' => 'companies#all_companies', :format => 'json'

  match '/kudos/:id' => 'kudos#give_kudos'
  match '/kudos/:id/profile' => 'kudos#give_kudos_from_profile'

  match '/jobs/start' => 'jobs#create_jobs'
  match '/jobs/create' => 'jobs#create_job'
  match '/jobs/load' => 'jobs#jobs', :format => 'json'
  match '/jobs/:job_type'  => 'jobs#all_jobs'
  match '/job/apply' => 'jobs#apply_job', :format => 'json'
  match '/job/contact_recruiter' => 'jobs#contact_recruiter'
  match '/job/share' => 'jobs#share'
  match '/job/forward' => 'jobs#forward'
  match '/job/update_user_status' => 'jobs#update_user_status'
  match '/job/:id' => 'jobs#show_job'
  match '/job/:id/status' => 'jobs#show_job_status'
  match '/job/app/:id/stats' => 'jobs#user_job_app_stats'
  match '/job/:id/edit' => 'jobs#edit_job'
  match '/job/:id/delete' => 'jobs#delete_job'
  match '/jobs/photo_upload' => 'jobs#job_photo_upload'

  match '/message/initiate' => 'messages#initiate_message'
  match '/message/:id' => 'messages#show_message'
  match '/message/:id/reply' => 'messages#reply_message'

  match '/questions' => 'questions#dash'
  match '/questions/create' => 'questions#handle_create_question'
  match '/questions/publish' => 'questions#publish_question'
  match '/questions/:id' => 'questions#show_question'
  match '/questions/:id/edit' => 'questions#edit_question '
  match '/question/follow/:id' => 'questions#follow_question'
  match '/question/unfollow/:id' => 'questions#unfollow_question'

  match '/categories/:category_id'  => 'collections#show_category'
  match '/collection/:collection_id/follow'  => 'collections#collection_follow', :format => 'json'
  match '/collection/:collection_id/unfollow'  => 'collections#collection_unfollow', :format => 'json'
  match '/collection/:slug_id/:collection_id'  => 'collections#show_collection_full', as: :show_collection_full
  match '/collection/:collection_id'  => 'collections#show_collection_full', as: :show_collection_full
  match '/collections/new(/:category_id)'  => 'collections#new'
  match '/collections/create'  => 'collections#create', :format => 'json'
  match '/collections/public'  => 'collections#public_collections', :format => 'json'
  match '/collections/:category_id'  => 'collections#collections_by_category'

app/models/post/article.rb
class Article
  include Mongoid::Document
  include LinkHelper
  field :title, type: String
  field :url, type: String
  field :tag_line, type: String
  field :description, type: String
  field :view_count, type: Integer
  field :date, type: Date
  field :majors, type: Array
  field :schools, type: Array
  field :external_url, type: String
  field :source, type: String
  field :photo_id, type: String
  field :video_id, type: String
  field :majors, type: Array
  field :author, type: String
  field :author_url, type: String
  field :company_id, type: String
  field :html, type: String
  field :type, type: String

  attr_accessible :title, :url, :tag_line, :description, :view_count,
                  :date, :majors, :schools, :external_url, :author,
                  :author_url, :html, :photo_id, :company_id, :video_id,
                  :type

  set_callback(:save, :after, if: (:title_changed? || :description_changed?)) do |document|
    SitemapPingerWorker.perform_async(get_story_url(self.author, self.id))
  end

  def article_url
    get_story_url(self.author, self.id)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesManager
  include FeedItemsManager
  include StoryHelper
  include UsersManager
  include SchoolsManager
  include CommonHelper

  def show_stories
    unless logged_in?
      return
    end
    @feed_items = FeedItems.where(:collection_id.exists => false, :poster_type => 'user', :type => 'story').to_a
    @public_collections = get_public_collections
  end

  def show_article
    @article = get_article(params[:id])
    rparams = params.except(:id)
    NotificationsLoggerWorker.perform_async('Consumer.Article.View',
                                            {handle: (current_user.blank?) ? 'public' : current_user[:handle],
                                             article_id: params[:id],
                                             params: rparams,
                                             ref: {referrer: params[:referrer],
                                                   referrer_id: params[:referrer_id],
                                                   referrer_type: params[:referrer_type],
                                                   meed_user_tracker: cookies[:meed_user_tracker]}
                                            })
    # Logging event in Intercom
    unless current_user.blank?
      IntercomLoggerWorker.perform_async('article-view', current_user[:_id].to_s, {
                                                           :article_id => params[:id],
                                                           :ref => {referrer: params[:referrer],
                                                                    referrer_id: params[:referrer_id],
                                                                    referrer_type: params[:referrer_type]}
                                                       })
    end
    if @article.blank?
      redirect_to root_path
    else
      update_article_views (@article.id)
      page_title(@article.title)
      @metadata = get_story_metadata(@article)
      unless @article[:company].blank? or current_user.blank?
        @article[:is_viewer_following] = is_user_following_company(current_user.handle, @article[:company].id)
      end
      respond_to do |format|
        format.html { return render layout: "angular_app", template: "angular_app/index" }
        format.json {
          return render json: {article: @article}
        }
      end
    end
  end

  def social_groups_track
    unless params[:id].blank?
      SocialChannels.where(_id: params[:id]).inc(:views, 1)
    end
  end

  def social_groups
    @school_channels = get_social_channels_for_school(get_school_handle_from_email(current_user.id))
    @fb_general_channels = Array.new
    @school_channels.each do |school_channel|
      if !school_channel.type.blank? and school_channel.type.eql? 'Facebook General Group'
        @fb_general_channels << school_channel
      end
    end
    @fb_general_channels.sort_by!(&:name)

    @fb_school_channels = Array.new
    @school_channels.each do |school_channel|
      if !school_channel.type.blank? and school_channel.type.eql? 'Facebook University Group'
        @fb_school_channels << school_channel
      end
    end
    @fb_school_channels.sort_by!(&:name)

    @linkedin_groups = Array.new
    @school_channels.each do |school_channel|
      if !school_channel.type.blank? and school_channel.type.downcase.eql? 'linkedin'
        @linkedin_groups << school_channel
      end
    end
    @linkedin_groups.sort_by!(&:name)

    @twitter_channels = Array.new
    @school_channels.each do |school_channel|
      if !school_channel.type.blank? and school_channel.type.downcase.eql? 'twitter'
        @twitter_channels << school_channel
      end
    end

    @twitter_channels.sort_by!(&:name)

  end

  def show_story
    article_id = params[:article_id]
    @article = ''
    if article_id.blank?
      return
    end
    @data = get_feed_item_for_subject_id(article_id, current_user)
    if @data.blank?
      return
    end
    @metadata = get_story_metadata(@data)
    page_title(@data.title)
    if cookies[article_id].blank?
      cookies[article_id] = true
      increment_feed_view_count(article_id)
    end
    rparams = params.except(:article_id)
    comments = get_comments_for_feed(current_user, @data.id)
    unless comments.blank?
      comments.each do |comment|
       if comment.description.eql? @data.caption
          comment.delete
          decrement_comment_count(@data.id)
        end
      end
    end
    @data[:comments] = comments
    @data[:short_url] = get_short_url(@data.url)
    @related_content = get_feed_items_for_user_stories(current_user).take(3)
    NotificationsLoggerWorker.perform_async('Consumer.Article.Story',
                                            {handle: (current_user.blank?) ? 'public' : current_user[:handle],
                                             article_id: article_id,
                                             params: rparams,
                                             ref: {referrer: params[:referrer],
                                                   referrer_id: params[:referrer_id],
                                                   referrer_type: params[:referrer_type],
                                                   meed_user_tracker: cookies[:meed_user_tracker]}
                                            })
    # Logging event in Intercom
    unless current_user.blank?
      IntercomLoggerWorker.perform_async('story-view', current_user[:_id].to_s, {
                                                         :article_id => article_id,
                                                         :ref => {referrer: params[:referrer],
                                                                  referrer_id: params[:referrer_id],
                                                                  referrer_type: params[:referrer_type]},
                                                     })
    end


    respond_to do |format|
      format.html { return render layout: "angular_app", template: "angular_app/index" }
      format.json {
        return render json: {article: @data, related_content: @related_content, metadata: @metadata}
      }
    end


  end

  def create_article
    unless logged_in?
      return
    end
    @majors = admin_all_majors
    @feed_item = FeedItems.new
    cookies[:dont_show_meediorite_modal] = true

    respond_to do |format|
      format.html{
        return render layout: "angular_app", template: "angular_app/index"
      }
    end
  end

end

app/views/articles/_related_stories.html.erb
<% unless @related_content.blank? %>
    <hr class="hr-profile-header">
    <div class="related_content" style="margin-top: 5px">
      <% @related_content.take(3).each do |content| %>
          <div class="article-container col-md-4 col-sm-4 col-xs-4" style="margin-top: 10px; opacity: 0.8">
            <div class="post-entry embed-styling border-blockquote" style="margin-top: 1vh">
              <div class="card article">
                <div class="bd" style="border-left-color: rgb(0, 0, 0);">
                  <div class="pair-bd">
                    <div class="art-bd">
                      <a target="_blank" href="<%= content.url %>?ssm=true" class="" style="padding-bottom: 46.8553459119497%; background-color: rgb(255, 255, 255);">
                        <img class="art-bd-img" src="<%= content.large_image_url %>" style="max-height: 15vh; display: inherit">
                      </a>
                    </div>
                    <div class="txt-bd" style="padding:0px">
                      <h4 class="title" style="margin:0px;">
                        <a target="_blank" href="<%= content.url %>?ssm=true" style="font-size: 16px;"><%= content.title.truncate(50) %></a>
                      </h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
      <div style="clear:both"></div>
    </div>
<% end %>

app/views/articles/_user_story.html.erb
<% unless data[:user].blank? %>
    <div class="blog-list blog-category-list" style="overflow: hidden">
      <article class="post col-md-12 col-sm-12 col-xs-12 col-md-offset-0 col-sm-offset-0 col-xs-offset-0" style="margin-bottom: 0px">
        <div>
          <div class="content feed-container">
            <div class="date-label">
              <a href="/<%= data[:user].handle %>">
                <% if !data[:user].blank? and data[:user].is_meediorite? %>
                    <div class="user-image-badge">M</div>
                <% end %>
                <% if data[:user][:image_url].blank? %>
                    <img class="img-responsive image-small" src="http://res.cloudinary.com/resume/image/upload/v1409877319/user_male4-128_q1iypj_lgzk5i.jpg">
                <% else %>
                    <img class="img-responsive image-small" src="<%= data[:user][:image_url] %>"/>
                <% end %>
              </a>
            </div>
            <div class="article-container col-md-8 col-sm-8 col-xs-8" style="padding-left: 0px;">
              <div id="link-<%= data.id %>" class="post-title">
                <a href="/<%= data[:user].handle %>"><%= data[:user].name %></a>
              </div>
              <div class="meta">
                <ul class="meta-list list-inline" style="border-bottom: none">
                  <li class="post-author">
                    —
                    <% if data[:user].headline.blank? %>
                        Class of <%= data[:user].year %> 
                    <% else %>
                        <%= data[:user].headline %> 
                    <% end %>
                  </li>
                </ul>
              </div>
            </div>
            <div class="article-container col-md-4 col-sm-4 col-xs-4">
              <div id="share_<%= data.id %>" class="social-share"></div>
            </div>
            <div style="clear:both"></div>
            <div class="post-entry embed-styling border-blockquote" style="margin-top: 1vh">
              <div class="card article">
                <div class="hdr">
                  <div>
                    <div style="line-height: 22px;"><%= data[:caption] %></div>
                  </div>
                </div>
                <hr class="hr-profile-item">
                <div class="bd" style="border-left-color: rgb(0, 0, 0);">
                  <div class="pair-bd">
                    <div class="art-bd">
                      <a target="_blank" href="<%= data.external_url %>" class="" style="padding-bottom: 46.8553459119497%; background-color: rgb(255, 255, 255);">
                        <img class="art-bd-img" src="<%= data.large_image_url %>" style="opacity: 1; max-height: 25vh; display: inherit">
                      </a>
                    </div>
                    <div class="txt-bd" style="padding:0px">
                      <div class="title" style="margin-bottom: 5px;margin-top: 5px;">
                        <a target="_blank" href="<%= data.external_url %>"><%= data.title %></a>
                      </div>
                      <p class="info-text-medium"><%= @data.description.truncate(500).html_safe %></p>
                    </div>
                  </div>
                </div>
              </div>
              <div>
                <% unless data.collections.blank? %>
                  <span class="glyphicon glyphicon-tag"> </span> <%= "#{data.collections.join(", ")}" %>
                <% end %>
              </div>
            </div>
            <div class="user-feed-actions" id="feed-actions-<%= position.blank? ? '' : "#{position}-" %><%= data[:_id] %>"> 
              <%= render 'feed/feed_actions', :data => data, :position => position %> 
            </div>
          </div>
        </div>
      </article>
    </div>
<% end %>

app/views/articles/show_article.erb
<% if current_user.blank? %>
    <%= render 'shared/signup_modal' %>
<% end %>
<div class="row-view">
	<% if @article.blank? %>
		<div class="profile-insight" style="text-align: center">
			<span> Doh! This article must have been deleted.</span>
		</div>
	<% end %>
	<% unless @article.blank? %>
		<div class="article-title">
			<% unless @article[:title].blank? %>
				<%= @article[:title].html_safe %>
			<% end %>
		</div>
		<hr class="hr-profile-item">
		<div class="row">
			<div class="job-details-company">
				<div class="company-title-small">
					<% unless @article[:company].blank? %>
						<% unless @article[:company][:company_logo].blank? %>
							<img src="<%= @article[:company][:company_logo] %>" class="img-responsive image-small">
						<% end %>
						<a href="<%= get_company_url(@article[:company][:_id]) %>"> <%= @article[:company][:name] %></a>
						<% if current_user.blank? %>
							<a href="/?reg=true" class="anchor-tag-button button-green" style="text-decoration: none; float: right">Follow
								Company</a>

						<% else %>
							<% unless @article[:is_viewer_following] %>
								<button class="button button-green" style="float: right;" id="follow_company_<%= @article[:company].id %>">Follow
									Company
								</button>
							<% end %>
						<% end %>
					<% end %>
					<hr class="hr-profile-item">
				</div>
				<% unless  @article[:photo].blank? or @article[:photo][:large_image_url].blank? %>
					<% if !@article[:type].blank? and @article[:type].eql? 'video' %>
						<div class="iframe-center">
							<% if @article[:source].downcase.eql? 'youtube' %>
								<div id="box_video" style="background:url(<%= @article[:photo][:large_image_url]%>) repeat center top fixed">
									<div id="overlay_video">
										<a href="https://www.youtube.com/embed/<%= @article[:video_id] %>?autoplay=1&controls=0&rel=0&showinfo=0" target="_blank">
											<span id="play__video__yt-article-<%= @article.id %>" class="play_video">►</span>
										</a>
									</div>
								</div>
							<% elsif @article[:source].downcase.eql? 'vimeo' %>
								<div id="box_video" style="background:url(<%= @article[:photo][:large_image_url]%>) repeat center top fixed">
									<div id="overlay_video">
										<a href="//player.vimeo.com/video/<%= @article[:video_id] %>?title=0&amp;byline=0&amp;portrait=0" target="_blank">
											<span id="play__video__vimeo-article-<%= @article.id %>" class="play_video">►</span>
										</a>
									</div>
								</div>
							<% end %>
						</div>
					<% elsif  @article[:type].eql? 'photo' %>
						<img id="box_photo_detail" src="<%= @article[:photo][:large_image_url] %>" />

					<% else %>
                      <img id="box_photo_detail" src="<%= @article[:photo][:large_image_url] %>" />

            <% end %>
				<% end %>
				<% if @article[:author].blank? %>
					<div class="article-heading" style="text-align: right">
						Source: <%= @article[:source] %>
					</div>
				<% else %>
					<div class="article-heading">
						Source: <a href="<%= @article[:author_url] %>"><%= @article[:author] %></a>
					</div>
				<% end %>
				<hr class="hr-profile-separator">
				<% unless @article[:html].blank? %>
					<div style="margin-top:2%" class="article-description">
						<%= @article[:html].html_safe %>
					</div>
					<hr class="hr-profile-separator">
				<% end %>
	<% end %>
	</div>
	<% unless @article[:external_url].blank? %>
		<div>
			Continue Reading.. <a href="<%= @article[:external_url] %>"> <%= @article[:external_url] %></a>
			<hr class="hr-profile-separator">
		</div>
	<% end %>
	</div>
</div>

app/views/articles/show_stories.html.erb
<% if @feed_items.blank? %>
    <div class="any-center">
      <div class="info-text-large-center" style="font-size: 24px;"> Nothing to show...!</div>
    </div>
<% else %>
    <% @feed_items.each do |feed_item| %>
        <% if feed_item.class.name.eql? Job.to_s %>
            <%= render 'jobs/view_dash_jobs', :job => feed_item %>
        <% else %>
            <% if feed_item[:poster_type].eql? 'company' %>
                <% unless feed_item[:company].blank? %>
                    <%= render 'feed/feed_item_render', :data => feed_item, :company => feed_item[:company], :position => '' %>
                <% end %>
            <% elsif feed_item[:poster_type].eql? 'product' %>
                <%= render 'feed/feed_item_render', :data => feed_item, :position => '' %>
            <% elsif feed_item[:poster_type].eql? 'user' %>
                <%= render 'feed/feed_item_render', :data => feed_item, :position => '' %>
            <% end %>
        <% end %>
    <% end %>
<% end %>