config/routes.rb
require 'sidekiq/web'
Futura::Application.routes.draw do
  resources :crm_results

  get 'home/index'
  root :to => 'home#index'
  resources :users, :only => [:create, :verify]

  match '/404' => 'application#page_not_found'
  match '/422' => 'application#server_error'
  match '/500' => 'application#server_error'
  match '/_=_' => 'home#index'

  match '/sitemap.:format', :controller => 'home', :action => 'sitemap', :conditions => {:method => :get}, as: 'sitemap'
  match '/seomagicsitemap.:format', :controller => 'home', :action => 'sitemap_all', :conditions => {:method => :get}, as: 'sitemap'
  match '/sitemap.xml' => 'home#sitemap'
  match '/seomagicsitemap.xml' => 'home#sitemap_all'
  match '/robots.txt' => 'home#robots', format: :text, as: :robots
  match '/promotion' => 'home#promotion'
  match '/fallcompetition' => 'home#competition'
  match '/fallcompetition/leaderboard' => 'home#competition_leaderboard'

  match 'users/incomplete' => 'users#incomplete'
  match 'users/incomplete/submit' => 'users#incomplete_submit'
  match 'users/linkedin/create' => 'users#linkedin_create'
  match 'users/linkedin/complete' => 'users#linkedin_complete'

  match 'users/forgot' => 'users#forgot'
  match 'users/password' => 'users#password'
  match 'users/password/submit' => 'users#passwordsubmit'
  match 'users/forgotme' => 'users#forgotme'
  match 'users/waitlist' => 'users#verify'
  match 'users/verify_easy' => 'users#verify_easy'
  match 'users/create_easy' => 'users#create_easy'
  match 'users/account_easy' => 'users#account_easy'
  match 'users/leaderboard' => 'users#leader_board' , :format => 'json'
  match '/leaderboard/show' => 'users#leader_board_show'
  match 'users/earnmeedpoints' => 'users#earn_meed_points'
  match 'users/promotion' => 'users#promotion'
  match 'users/verify' => 'users#verify'
  match 'users/verify/again' => 'users#verifyagain'
  match 'users/checkhandle/:handle' => 'users#check_handle'
  match 'users/get_current_user' => 'users#get_current_user', :format => 'json'
  match 'users/increment/meed_points' => 'notifications#increment_meed_points', :format => 'json'
  match '/invites' => 'users#invite'
  match '/login' => redirect("/")
  match '/enterprise-signup' => 'home#enterprise_pointer'

  match '/emails/unsubscribe' => 'home#unsubscribe'
  match '/emails/subscribe' => 'home#subscribe'
  match '/jobs' => 'home#dash'
  match '/contactus' => 'home#contact_us'
  match '/contact' => 'home#contact'
  match '/ftue/update' => 'first_user_experiences#ftue_update'
  match '/about/product' => 'home#about_product'
  match '/about/version' => 'home#show_version'
  match '/school/verify' => 'schools#verify'
  match '/school/:school_id' => 'schools#index'
  match '/school/lookup/email' => 'schools#lookup', :format => 'json'
  match 'users/account' => 'users#account', :format => 'json'
  match 'users/influencers/account' => 'users#influencer_account', :format => 'json'
  match 'users/influencers/expertise/save' => 'users#influencer_expertise_save', :format => 'json'
  match 'users/create' => 'users#create'
  match '/login/verify' => 'sessions#create'

  match '/majors' => 'majors#index'
  match '/majors/degrees' => 'majors#majors_degrees', :format => 'json'
  match '/majors/types' => 'majors#majors_types', :format => 'json'

  match '/insights' => 'home#insights'
  match '/questions' => 'questions#dash'
  match '/connections' => 'connections#start'
  match '/connections/gmail' => 'connections#gmail_import'
  match '/connections/save' => 'connections#save'
  match '/connections/invited' => 'connections#invited'
  match '/contacts/failure' => 'connections#failure'
  match 'contacts/gmail/callback' => 'connections#gmail_import_callback'
  match 'contacts/auth/gmail' => 'connections#gmail_import_auth'
  match '/track/click/:data' => 'tracking#track_click'

  match '/auth/linkedin/callback' => 'sessions#social_sign_up', :format => 'json'
  match '/auth/github/callback' => 'sessions#social_sign_up'
  match '/auth/twitter/callback' => 'sessions#social_sign_up'
  match '/auth/callback' => 'sessions#social_sign_up', :format => 'json'

  match '/auth/linkedin/' => 'profiles#linkedin_import'
  match '/auth/twitter/' => 'profiles#linkedin_import'
  match '/auth/github/' => 'profiles#linkedin_import'
  match '/resume/upload/' => 'profiles#resume_upload', :format => 'json'

  match '/auth/failure' => 'profiles#linkedin_failure'

  match '/settings' => 'home#settings'
  match '/settings/:id/update' => 'home#update_settings'
  match '/settings/deactivate_survey' => 'home#deactivate_survey'

  match '/post/publish' => 'posts#publish_story'
  match '/post/job' => 'posts#post_job'
  match '/post/:id/update' => 'posts#update_story'
  match '/show/stories' => 'articles#show_stories'
  match '/scrape' => 'scrape#scrape'

  match '/invite' => 'home#invite_users'
  match '/waitlist/add' => 'home#add_waitlist_users'
  match '/invite/friends' => 'home#invite_users_mini'
  match '/facebook/friends/save' => 'connections#save_facebook'
  match '/ineedmeed' => 'home#need_meed'
  match '/waitlist_status' => 'home#need_meed_status'
  match '/waitlist/verify' => 'users#waitlist_verify'

  match '/hackathon/:id' => 'hackathon#show'
  match '/home' => 'home#dash'
  match '/activity' => 'feed#activity'
  match '/feed' => 'feed#feed'
  match '/submit/post(/:collection_id)' => 'articles#create_article', as: :create_article
  match '/articles/publish' => 'articles#publish_article'
  match '/articles/:id' => 'articles#show_article'
  match '/articles/:id/edit' => 'articles#edit_article'

  match '/logout' => 'sessions#destroy'
  match '/demigod/usc_auto_session' => 'sessions#demo'
  match '/edit' => 'profiles#edit'
  match '/view' => 'profiles#view'
  match '/share' => 'profiles#share'
  match '/meedfair' => 'home#careerfair'
  match '/jobinbox' => 'home#dash'
  match '/messages' => 'messages#messages'
  match '/profile' => 'profiles#profile'
  match '/influencers' => 'influencers#index'

  match '/:id/collection/:slug_id/:collection_id'  => 'collections#show_collection_full', as: :show_collection_full
  match '/:id/ama/:event_id' => 'profiles#view', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id' => 'profiles#view', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/follow' => 'profiles#follow_user', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/unfollow' => 'profiles#unfollow_user', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/invite' => 'profiles#invite_user', :constraints => {:id => /[^\/]*/}, as: 'user'

  match '/:id/:year/:month/:day/:article_id' => 'articles#show_story', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/story/:id/:year/:month/:day/:article_id' => 'articles#show_story', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/auth' => 'profiles#auth_view', :constraints => {:id => /[^\/]*/}, as: 'user'
  match '/:id/contact' => 'profiles#contact_profile'
  match '/:id/contact/email' => 'profiles#send_email'
  match '/:id/viewers' => 'home#viewers'
  match '/:id/jobviews' => 'home#job_views'

  match '/ama/vmk-google' => 'events#show_ama'
  match '/ama/follow/:ama_id' => 'events#follow_ama'
  match '/user/recommendations'  => 'users#recommended_users', :format => 'json'
  match '/user/lead/recommendations'  => 'users#recommended_lead_users', :format => 'json'

  match '/profiles/objective/save' => 'profiles#save_objective'
  match '/profiles/bio/save' => 'profiles#save_bio'
  match '/profiles/headline/save' => 'profiles#save_headline'
  match '/profiles/publication/save' => 'profiles#save_publication'
  match '/profiles/internship/save' => 'profiles#save_internship'
  match '/profiles/course/save' => 'profiles#save_course'
  match '/profiles/experience/save' => 'profiles#save_experience'
  match '/profiles/education/save' => 'profiles#save_education'
  match '/profiles/header/save' => 'profiles#save_header'
  match '/profiles/photo/save' => 'photos#save_profile_photo'
  match '/articles/photo/save' => 'photos#save_article_photo'
  match '/feed/files/save' => 'feed#save_meed_files'

  match '/profiles/course/invites/:course_id' => 'courses#course_invites', :format => 'json'
  match '/course/invite/:invite_id/remind' => 'courses#invite_reminder', :format => 'json'
  match '/course/invite' => 'courses#create_invite', :format => 'json'

  match '/profiles/bundle' => 'profiles#show_profile_bundle'
  match '/comments/show' => 'comments#show_comments'
  match '/comments/create' => 'comments#create'
  match '/comments/:id/update' => 'comments#update'
  match '/comments/delete' => 'comments#delete'

  match '/company/:id' => 'companies#view', :constraints => {:id => /[^\/]*/}
  match '/company/follow/:id' => 'companies#follow', :constraints => {:id => /[^\/]*/}
  match '/company/:id/auth' => 'companies#auth_view', :constraints => {:id => /[^\/]*/}
  match '/company/unfollow/:id' => 'companies#unfollow', :constraints => {:id => /[^\/]*/}
  match '/user/company/recommendations'  => 'companies#recommended_companies', :format => 'json'
  match '/company/list/all' => 'companies#all_companies', :format => 'json'

  match '/kudos/:id' => 'kudos#give_kudos'
  match '/kudos/:id/profile' => 'kudos#give_kudos_from_profile'

  match '/jobs/start' => 'jobs#create_jobs'
  match '/jobs/create' => 'jobs#create_job'
  match '/jobs/load' => 'jobs#jobs', :format => 'json'
  match '/jobs/:job_type'  => 'jobs#all_jobs'
  match '/job/apply' => 'jobs#apply_job', :format => 'json'
  match '/job/contact_recruiter' => 'jobs#contact_recruiter'
  match '/job/share' => 'jobs#share'
  match '/job/forward' => 'jobs#forward'
  match '/job/update_user_status' => 'jobs#update_user_status'
  match '/job/:id' => 'jobs#show_job'
  match '/job/:id/status' => 'jobs#show_job_status'
  match '/job/app/:id/stats' => 'jobs#user_job_app_stats'
  match '/job/:id/edit' => 'jobs#edit_job'
  match '/job/:id/delete' => 'jobs#delete_job'
  match '/jobs/photo_upload' => 'jobs#job_photo_upload'

app/views/home/_dash_panel.html.erb
<% unless alert.blank? %>
    <div class="alert alert-info alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= alert %>
    </div>
<% end %>
<div id="content">
  <ul id="allTabs" class="nav nav-tabs nav-justified" data-tabs="tabs">
    <li id="myfeed" class="active" ><a href="#feed" data-toggle="pill"><span class="fa fa-group"></span> My Feed</a></li>
    <li id="show_jobs">
      <a href="#jobs" data-toggle="pill" data-intro="Jobs for you" data-position="bottom" data-tier="home-1">
        <span class="glyphicon glyphicon-briefcase"></span> Jobs
      </a>
    </li>
  </ul>
  <div id="all-tab-content" class="tab-content">
    <div class="tab-pane fade in active" id="feed">
      <%= render 'feed/render_feed_items' %>
    </div>
    <div class="tab-pane fade in" id="jobs">
      <%= render 'jobs/render_jobs' %>
    </div>
  </div>
</div>
<script>
  $(document).ready(function () {
    loadJobs('all');
    loadFeed('all');
  });
</script>

app/views/home/about_product.html.erb
<% if current_user.blank? %>
    <p class="article-banner-ad">
      <span>Are you a current student or college grad?</span>
      <a href="/" style="font-weight: bold"> Sign Up</a>
      for Meed
    </p>
<% end %>
 <hr class="hr-header">
<p class="accordion lightbox-text">How to hire from Universities? <br/> <span class="info-text-large">(For Employers)</span>
</p>
<hr class="hr-header">
<div class="form-view" align="center">
  <ul style="list-style-type:none">
    <li class="list-jobs">
      <hr class="job-create-hr">
      <p class="job-create-heading">
        <span> 1.</span> Post jobs to top universities filtered by majors — <a href="/jobs/start">here</a>.
      </p>
      <hr class="job-create-hr">
    </li>
    <li>
    </li>
    <li class="list-jobs">
      <span><img class="img-border" src="<%= asset_path 'product_explanation_schools.png' %>"></span>
    </li>
    <li class="list-jobs">
      <hr class="job-create-hr">
      <p class="job-create-heading">
         2. Track/download resumes from all schools with a simple link —
      </p>
      <hr class="job-create-hr">
    </li>
    <li class="list-jobs">
      <span><img class="img-border" src="<%= asset_path 'product_explanation_job_status.png' %>"></span>
    </li>
    <li class="list-jobs">
      <hr class="job-create-hr">
      <p class="job-create-heading">
          3. Get email notification for each and every application —
      </p>
      <hr class="job-create-hr">
    </li>
    <li class="list-jobs">
      <span><img class="img-border" src="<%= asset_path 'product_explanation_email.png' %>"></span>
    </li>
    <li class="list-jobs">
      <hr class="job-create-hr">
      <p class="job-create-heading">
         4. Promote your company culture and build brand —
      </p>
      <hr class="job-create-hr">
    </li>
    <li class="list-jobs">
      <span><img class="img-border" src="<%= asset_path 'product_explanation_culture.png' %>"></span>
    </li>
  </ul>
</div>

app/views/home/careerfair.html.erb
<div class="bg-slider-wrapper">
  <div class="flexslider bg-slider">
    <ul class="slides">
      <li class="slide careerfair-3"></li>
      <li class="slide careerfair-4"></li>
      <li class="slide careerfair-2"></li>
      <li class="slide careerfair-1"></li>
    </ul>
  </div>
</div>
<!--//bg-slider-wrapper-->

<section class="promo section section-on-bg" data-sr='enter bottom and scale up 20% over 1s and reset'>
  <div class="container text-center">
    <div class="any-center">
      <img src="https://res.cloudinary.com/resume/image/upload/c_scale,w_120/v1427155934/crescent_green_rt6rit.png" style="padding: 20px;">
    </div>
    <h2 class="title" style="line-height: 1.1;">Meed Fair</h2>

    <p class="intro text-center"><span style="font-weight: bold; font-size:20px">Deadline
      for applications — June 5th</span>
    </p>

    <%= form_tag({:controller => 'users', :action => 'verify'}, :class => 'signup-form navbar-form', :html => {:multipart => true}) do %>
        <%= hidden_field_tag :source, 'meed_fair' %>
        <div class="form-group">
          <%= text_field_tag :email, nil, :required => '', :class => 'form-control', :id => 'sign_up_tb', :style => 'height:50px;', :placeholder => 'Enter school email (ex: sam@usc.edu)' %>
        </div>
        <%= button_tag(type: 'submit', class: 'btn btn-cta btn-cta-primary', :id => 'sign_up_tb', :data => {:disable_with => 'Verifying.. '}) do %>
            Get In
        <% end %>
        <p>
        </p>

        <div class="col-md-2 col-md-offset-4">
          <% if !alert.blank? %>
              <p class="label label-important">
                <%= alert %>
              </p>
          <% end %>
        </div>
    <% end -%>
  </div>
</section>
<!--//promo-->

<div class="sections-wrapper">
  <section id="cta-section" class="section cta-section text-center home-cta-section">

    <div class="container">
      <h2 class="title">
        <p> Elite <span class="counting">companies</span> participating
        </p>
      </h2>
    </div>
    <div class="university-container-main">
      <div class="university">
        <a href="/zenefits"><img class="image-medium company-picture-holder" src="https://www.filepicker.io/api/file/ww6DAdroQ5qCOShRy43e/convert?w=100"></a>
      </div>
      <div class="university">
        <a href="/leapmotion"><img class="image-medium company-picture-holder" src="https://www.filepicker.io/api/file/8qNKIrOoQq6u4f86SEkU/convert?w=100"></a>

      </div>
      <div class="university">
        <a href="/6sense"><img class="image-medium company-picture-holder" src="https://www.filepicker.io/api/file/RhHYTdqhTyiJ7hbv9bye/convert?w=100"></a>

      </div>
      <div class="university">
        <a href="/planet"><img class="image-medium company-picture-holder" src="https://www.filepicker.io/api/file/VEujPgKHTaGj2GFYsSV6/convert?w=100"></a>

      </div>
      <div class="university">
        <a href="/tint"><img class="image-medium company-picture-holder" src="http://res.cloudinary.com/resume/image/upload/v1393791805/bitate1zzgxmylaxejca.jpg"></a>

      </div>
      <div class="university">
        <a href="/sungevity"><img class="image-medium company-picture-holder" src="https://www.filepicker.io/api/file/25E7dSvQZaBcj0hRAmYV/convert?w=100"></a>

      </div>
      <div class="university">
        <a href="/hatchtodaysf">
          <img class="image-medium company-picture-holder" src="https://www.filepicker.io/api/file/bqugznYBSI6gNF7Pgzyx/convert?w=100"></a>
      </div>

      <div class="university">
        <a href="/quora"><img class="image-medium company-picture-holder" src="http://res.cloudinary.com/resume/image/upload/v1406667381/ynyylhry19xxbvcogxwj.png"></a>

      </div>
      <div class="university">
        <a href="/resu.me">
          <img class="image-medium company-picture-holder" src="https://www.filepicker.io/api/file/KbLSOloFSTKUlb4hqy3a/convert?w=100"></a>
      </div>
    </div>
  </section>
  <!--//cta-section-->
  <div class="sections-wrapper">
    <section id="cta-section" class="section cta-section text-center home-cta-section">

      <div class="container">
        <h2 class="title">Exclusive to <span class="counting">28</span> Universities only!</h2>
      </div>
      <div class="university-container-main">
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403398763/https_fbcdn-sphotos-e-a_akamaihd_net_hphotos-ak-xaf1_t1_0-9_10247472_784138694943918_2566252489225535785_n_pn7zvj.jpg">

          <p>University of Southern California</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403398541/https_fbcdn-sphotos-b-a_akamaihd_net_hphotos-ak-xpa1_t1_0-9_10291852_10152192154145958_3670918893082090246_n_fy6vb5.png">

          <p>University of California, Los Angeles</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403398946/https_scontent-a_xx_fbcdn_net_hphotos-xpa1_t1_0-9_10154268_10152324234159661_7811345513940021516_n_jcpbot.jpg">

          <p>University of California, Berkeley</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403399006/https_fbcdn-sphotos-c-a_akamaihd_net_hphotos-ak-xap1_t1_0-9_1511295_10151884909689632_1673995846_n_vfuu7l.jpg">

          <p>University of Florida</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403399242/http_mastersinhealthinformatics_com_wp-content_uploads_2011_11_Northwestern-University-Logo_lo2yaw.jpg">

          <p>Northwestern University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403399300/https_fbcdn-sphotos-f-a_akamaihd_net_hphotos-ak-xfa1_t1_0-9_1044164_10151662970763418_1682551420_n_btnjgf.png">

          <p>Stanford University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="https://res.cloudinary.com/resume/image/upload/v1403399344/https_fbcdn-sphotos-b-a_akamaihd_net_hphotos-ak-xaf1_t1_0-9_1148800_680835795293388_126913444_n_ieenqc.png">

          <p>Massachusetts Institute of Technology</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403399502/https_fbcdn-sphotos-e-a_akamaihd_net_hphotos-ak-xap1_t1_0-9_1497662_10152559597990550_2006972615_n_aabclv.jpg">

          <p>Rice University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403399588/https_scontent-b_xx_fbcdn_net_hphotos-xfp1_t1_0-9_1977299_10151885273256534_1030627330_n_x6zng7.png">

          <p>Brown University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403399750/https_scontent-b_xx_fbcdn_net_hphotos-xfa1_t1_0-9_423332_10150531052446475_2102094817_n_bv2rgq.jpg">

          <p>Duke University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403399806/https_scontent-a_xx_fbcdn_net_hphotos-xaf1_t31_0-8_10380039_10152049890301607_8853146182777969742_o_jopvij.png">

          <p>Harvard University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403399928/https_scontent-a_xx_fbcdn_net_hphotos-xfa1_t1_0-9_4852_107717938936_1288057_n_n90jh3.jpg">

          <p>Columbia University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403399864/https_fbcdn-sphotos-g-a_akamaihd_net_hphotos-ak-xpa1_t1_0-9_1461114_10152120743001388_97498385_n_s1ihik.png">

          <p>Carnegie Mellon University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403400049/https_fbcdn-sphotos-f-a_akamaihd_net_hphotos-ak-prn2_t1_0-9_552699_10151136829178689_449718517_n_ldlnva.jpg">

          <p>New York University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403400096/https_scontent-a_xx_fbcdn_net_hphotos-xfp1_t1_0-9_227563_10150253568700320_5332225_n_lb5zkb.jpg">

          <p>Yale University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403400161/https_fbcdn-sphotos-g-a_akamaihd_net_hphotos-ak-frc1_t1_0-9_285709_10150894511456274_1637082454_n_zgbwaa.jpg">

          <p>University of Washington</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403419404/http_upload_wikimedia_org_wikipedia_commons_thumb_9_92_UPenn_shield_with_banner_svg_250px-UPenn_shield_with_banner_svg_hfilnr.png">

          <p>University of Pennsylvania</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403419486/https_fbcdn-sphotos-b-a_akamaihd_net_hphotos-ak-frc3_t1_0-9_995570_10151865306493671_1168153659_n_xklypd.png">

          <p>University of Massachusetts Amherst</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1403419799/https_fbcdn-sphotos-h-a_akamaihd_net_hphotos-ak-ash2_t1_0-9_551193_10150970949386930_1041310064_n_rivqnl.jpg">

          <p>The University of Texas at Austin</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1408822710/http_i_imgur_com_g0kdB1T_jqrhzr.jpg">

          <p>University of Waterloo</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/c_scale,w_180/v1408821782/https_coursera-university-assets_s3_amazonaws_com_70_de505d47be7d3a063b51b6f856a6e2_New-Block-M-Stacked-Blue-295C_600x600_s6daju.png">

          <p>University of Michigan</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1408823721/http_businessofcollegesports_com_wp-content_uploads_2012_03_ucsd-tritons_g61uxy.jpg">

          <p>University of California, San Diego</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1418070519/http_www_caltech_edu_sites_all_themes_caltech_mte_img_caltech_logo_ypkjoo.jpg">

          <p>California Institute of Technology</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1418070742/https_lh3_googleusercontent_com_-2jofGt-kQZk_AAAAAAAAAAI_AAAAAAAAKG8_AEw24vbiblA_s120-c_photo_bnhf4c.png">

          <p>Cornell University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1418070800/https_lh5_googleusercontent_com_-q0gRK-mwssI_AAAAAAAAAAI_AAAAAAAACsY_ZDo-TbmjMT8_s120-c_photo_g3dhbh.jpg">

          <p>Georgia Institute of Technology</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1418070841/http_t3_gstatic_com_images_q_tbn_ANd9GcSM9Eu2Fw1ahuF4hXShslBAk2ZbWxvesSKlbCVckNXGLb3z73VXKg_non4yv.jpg">

          <p>University of Illinois, Urbana-Champaign</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="http://res.cloudinary.com/resume/image/upload/v1418070899/https_lh4_googleusercontent_com_-eJ6mEvslTq8_AAAAAAAAAAI_AAAAAAAAA7s_IWNb8J2dy80_s120-c_photo_ftlvjr.png">

          <p>Princeton University</p>
        </div>
        <div class="university">
          <img class="image-rounded img-circle" src="https://res.cloudinary.com/resume/image/upload/c_scale,w_200/v1424750127/http_socialcomputing.uci.edu_sites_default_files_logos_uci_j6upda.jpg">

          <p>University of California, Irvine</p>
        </div>
      </div>
    </section>
    </div>
</div>

app/views/home/competition_leaderboard.html.erb
<p class="accordion lightbox-text">
  Fall Competition — Leader Board
</p>
<hr class="hr-header">

<div class="form-view">
  <table class="row-view">
    <tr class="profile-insight" style="text-align: center">
      <p class="info-text-large" style="text-align: center">
        This week's leader board for fall <a href="/fallcompetition">competition</a> is coming up, keep checking this space!
      </p>
    </tr>
  </table>
</div>

app/views/home/robots.text.erb
Sitemap: <%= sitemap_url %>

app/views/home/show_version.html.erb
<div class="row">
  <%= render 'shared/render_ftue' %>
</div>